# Generated by Django 5.0.4 on 2024-04-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="pdf_documents/")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_files",
                        to="blog.document",
                    ),
                ),
            ],
        ),
    ]
