# Generated by Django 5.0.4 on 2024-04-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_document_pdf_file_document_created_at_pdffile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
