# Generated by Django 5.0.4 on 2024-04-28 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_document_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdffile",
            name="document",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="PDFFile",
        ),
    ]
